# Generated by Django 5.2.9 on 2026-03-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='emi_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
