# Generated by Django 5.2.9 on 2026-03-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_payment_emi_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapproval',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-28'),
            preserve_default=False,
        ),
    ]
